Repository Starteryou-com/RevampUI, pull requests merged in 2024-10, with the labels that each got.

#5 Job Portal Page by Asif
  Starteryou/public/JobPortalPage/Placeholder Image.png
  Starteryou/public/JobPortalPage/StarVector.svg
  Starteryou/public/JobPortalPage/Vector.svg
  Starteryou/public/JobPortalPage/portalHero.svg
  Starteryou/src/App.jsx
  Starteryou/src/components/JobPortal/DiscoverPath.jsx
  Starteryou/src/components/JobPortal/HeroJobPortal.jsx
  Starteryou/src/components/JobPortal/JobListing.jsx
  Starteryou/src/components/JobPortal/LatestInsight.jsx
  Starteryou/src/components/JobPortal/LaunchBanner.jsx
  Starteryou/src/components/JobPortal/PathStart.jsx
  Starteryou/src/components/JobPortal/UnlockPotential.jsx
  Starteryou/src/pages/JobPortalPage.jsx
Labels: enhancement

#4 Add HTTPS support and Docker setup instructions
  Starteryou/Dockerfile
  Starteryou/nginx.conf
Labels: documentation

#9 Create main.yml
  .github/workflows/main.yml
Labels: enhancement

#11 Admin routes and File upload features
  Starteryou/package-lock.json
  Starteryou/package.json
  Starteryou/src/App.jsx
  Starteryou/src/components/About/BetterFuture.jsx
  Starteryou/src/components/About/HeroAbout.jsx
  Starteryou/src/components/About/OurMission.jsx
  Starteryou/src/components/About/OurVision.jsx
  Starteryou/src/components/About/Team.jsx
  Starteryou/src/components/AdminProtectedRoute.jsx
  Starteryou/src/components/FileUpload.jsx
  Starteryou/src/components/JobPortal/DiscoverPath.jsx
  Starteryou/src/components/JobPortal/HeroJobPortal.jsx
  Starteryou/src/components/JobPortal/JobListing.jsx
  Starteryou/src/components/JobPortal/LatestInsight.jsx
  Starteryou/src/components/JobPortal/LaunchBanner.jsx
  Starteryou/src/components/JobPortal/UnlockPotential.jsx
  Starteryou/src/components/Landing/BestBuddy.jsx
  Starteryou/src/components/Landing/BestJob.jsx
  Starteryou/src/components/Landing/BestJob2.jsx
  Starteryou/src/components/Landing/BestJob3.jsx
  Starteryou/src/components/Landing/BestJob4.jsx
  Starteryou/src/components/Landing/Collab.jsx
  Starteryou/src/components/Landing/Hero.jsx
  Starteryou/src/components/Landing/Pricing.jsx
  Starteryou/src/components/Landing/UpcomingFeatures.jsx
  Starteryou/src/components/LoginPage.jsx
  Starteryou/src/components/Navbar.jsx
  Starteryou/src/context/NavigationContext.jsx
  Starteryou/src/context/ProtectedRoute.jsx
  Starteryou/src/context/UserContext.jsx
Labels: enhancement

#14 PR for Job Page 2
  Starteryou/index.html
  Starteryou/public/JobPage/JobHome.svg
  Starteryou/src/App.jsx
  Starteryou/src/components/JobPage/AppSupport.jsx
  Starteryou/src/components/JobPage/DiscoverFuture.jsx
  Starteryou/src/components/JobPage/IdealJob.jsx
  Starteryou/src/components/JobPage/JobHero.jsx
  Starteryou/src/components/JobPage/Reviews.jsx
  Starteryou/src/components/JobPage/TailoredJob.jsx
  Starteryou/src/pages/JobPage.jsx
Labels: enhancement

#19 Backend Implementation Using NodeJS and MongoDB
  .DS_Store
  Starteryou/backend/.env
  Starteryou/backend/config/db.js
  Starteryou/backend/dockerfile
  Starteryou/backend/models/FileMetadata.js
  Starteryou/backend/package-lock.json
  Starteryou/backend/package.json
  Starteryou/backend/routes/fileRoutes.js
  Starteryou/backend/server.js
  Starteryou/src/components/Landing/Banner.jsx
  Starteryou/src/components/Landing/BestBuddy.jsx
  Starteryou/src/components/Landing/BestJob.jsx
  Starteryou/src/components/Landing/BestJob2.jsx
  Starteryou/src/components/Landing/BestJob3.jsx
  Starteryou/src/components/Landing/BestJob4.jsx
  Starteryou/src/components/Landing/Blog.jsx
  Starteryou/src/components/Landing/Collab.jsx
  Starteryou/src/components/Landing/Contact.jsx
  Starteryou/src/components/Landing/Hero.jsx
  Starteryou/src/components/Landing/Pricing.jsx
  Starteryou/src/components/Landing/UpcomingFeatures.css
  Starteryou/src/components/Landing/UpcomingFeatures.jsx
Labels: good first issue

#21 Doing Backend changes for docker file with node.js api
  .vscode/launch.json
  Starteryou/backend/.env
  Starteryou/backend/config/db.js
  Starteryou/backend/dockerfile
  Starteryou/backend/routes/fileRoutes.js
  Starteryou/backend/server.js
  Starteryou/docker-compose.yml
  Starteryou/nginx.conf
Labels: bug
